site_name: Meine ProManage-Dokumentation
site_url: https://promanage-doc.example
theme:
  name: material
  palette:
  #Dark Mode
  - scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to light mode
      primary: red
      accent: green

  #Light Mode
  - scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
      primary: green
      accent: purple

  font:
    text: Source Serif 4
    code: Roboto Mono

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

      